Add tile to toggle all animations (close #24)
mustafa01ali/Dev-Tiles pull request #25
Opened 2017-10-08 05:20 UTC by devesh-shetty

2017-10-08 17:24 UTC, mustafa01ali requested changes
Looks good @devesh-shetty, just a couple of minor comments. Also, please sync your fork and rebase it off of development for a clean diff.

2017-10-08 17:24 UTC, mustafa01ali commented on app/src/main/kotlin/xyz/mustafaali/devqstiles/MainActivity.kt
> +                Feature("Toggle Animation Scale", "Toggle window animation scale, transition animation scale, and animator duration scale", R.drawable.ic_animation)
Update to `("Toggle all animations", "Enable/disable all animations with one click, perfect for running Espresso tests, ....)`

2017-10-08 17:24 UTC, mustafa01ali commented on app/src/main/AndroidManifest.xml
> +            android:label="@string/label_toggle_animation_scale"
Change this to "Toggle all animations"

2017-10-09 02:33 UTC, devesh-shetty commented
@mustafa01ali changes done!

2017-10-09 22:59 UTC, mustafa01ali approved these changes

2017-10-09 23:00 UTC, merged

2019-06-26 17:24 UTC, 1043465747 commented
Bink-dev  كم رصيدي ف البنك